[project]
name = "week-6-cnns"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.5",
    "notebook>=7.4.4",
    "numpy>=2.1.3",
    "tensorflow>=2.19.0",
]
